/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PaModal {
        "heading": string;
        "open": boolean;
        "openModal": () => Promise<void>;
    }
}
declare global {
    interface HTMLPaModalElement extends Components.PaModal, HTMLStencilElement {
    }
    var HTMLPaModalElement: {
        prototype: HTMLPaModalElement;
        new (): HTMLPaModalElement;
    };
    interface HTMLElementTagNameMap {
        "pa-modal": HTMLPaModalElement;
    }
}
declare namespace LocalJSX {
    interface PaModal {
        "heading"?: string;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "pa-modal": PaModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pa-modal": LocalJSX.PaModal & JSXBase.HTMLAttributes<HTMLPaModalElement>;
        }
    }
}
